// ============================================================================
// fBoxLib/grains/FloatVariants.cpp -- generated distinct FP leaves (1 per
// opcode.func). GENERATED by codegen/gen_fp_leaves.py -- edit the generator,
// not this file. Copyright (C) 2025, 2026 eNVy Systems, Inc.
// ============================================================================
#include "coreLib/BoxResult.h"
#include "coreLib/ExecCtx.h"
#include "coreLib/InstructionGrain.h"
#include "coreLib/axp_attributes_core.h"
#include "coreLib/CpuState.h"
#include "fBoxLib/grains/FpExec.h"
#include "fpBoxLib/fp_backend.h"
#include "fpBoxLib/fp_backend_active.h"
#include <bit>
#include <cstdint>

namespace fBox {
using coreLib::BoxResult; using coreLib::ExecCtx; using coreLib::InstructionGrain;

// Local copy of Float.cpp's fpWrite (that one has internal linkage). Commits a
// 64-bit value to FP register Fc (encoded[4:0]) and propagates semantic flags.
namespace {
AXP_HOT AXP_FLATTEN
BoxResult fpWrite(InstructionGrain const& g, uint64_t value) noexcept {
    BoxResult r;
    r.semFlags      = g.semFlags;
    r.regWriteIdx   = static_cast<uint8_t>(g.encoded & 0x1Fu);
    r.regWriteIsFp  = true;
    r.regWriteValue = value;
    return r;
}
}  // anonymous namespace

// CMPTUN
AXP_HOT AXP_FLATTEN
auto execCmptun(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpT(fpBox::FpCompare::Un, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS
AXP_HOT AXP_FLATTEN
auto execCvtts(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTST
AXP_HOT AXP_FLATTEN
auto execCvtst(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtST(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ
AXP_HOT AXP_FLATTEN
auto execCvttq(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS
AXP_HOT AXP_FLATTEN
auto execCvtqs(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT
AXP_HOT AXP_FLATTEN
auto execCvtqt(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_C
AXP_HOT AXP_FLATTEN
auto execCvttsC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_M
AXP_HOT AXP_FLATTEN
auto execCvttsM(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_D
AXP_HOT AXP_FLATTEN
auto execCvttsD(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_UC
AXP_HOT AXP_FLATTEN
auto execCvttsUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_UM
AXP_HOT AXP_FLATTEN
auto execCvttsUm(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_U
AXP_HOT AXP_FLATTEN
auto execCvttsU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_UD
AXP_HOT AXP_FLATTEN
auto execCvttsUd(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SUC
AXP_HOT AXP_FLATTEN
auto execCvttsSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SUM
AXP_HOT AXP_FLATTEN
auto execCvttsSum(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SU
AXP_HOT AXP_FLATTEN
auto execCvttsSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SUD
AXP_HOT AXP_FLATTEN
auto execCvttsSud(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SUIC
AXP_HOT AXP_FLATTEN
auto execCvttsSuic(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SUIM
AXP_HOT AXP_FLATTEN
auto execCvttsSuim(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SUI
AXP_HOT AXP_FLATTEN
auto execCvttsSui(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTS_SUID
AXP_HOT AXP_FLATTEN
auto execCvttsSuid(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_C
AXP_HOT AXP_FLATTEN
auto execCvttqC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_M
AXP_HOT AXP_FLATTEN
auto execCvttqM(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_D
AXP_HOT AXP_FLATTEN
auto execCvttqD(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_VC
AXP_HOT AXP_FLATTEN
auto execCvttqVc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_VM
AXP_HOT AXP_FLATTEN
auto execCvttqVm(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_V
AXP_HOT AXP_FLATTEN
auto execCvttqV(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_VD
AXP_HOT AXP_FLATTEN
auto execCvttqVd(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SVC
AXP_HOT AXP_FLATTEN
auto execCvttqSvc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SVM
AXP_HOT AXP_FLATTEN
auto execCvttqSvm(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SV
AXP_HOT AXP_FLATTEN
auto execCvttqSv(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SVD
AXP_HOT AXP_FLATTEN
auto execCvttqSvd(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SVIC
AXP_HOT AXP_FLATTEN
auto execCvttqSvic(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SVIM
AXP_HOT AXP_FLATTEN
auto execCvttqSvim(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SVI
AXP_HOT AXP_FLATTEN
auto execCvttqSvi(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTTQ_SVID
AXP_HOT AXP_FLATTEN
auto execCvttqSvid(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtTQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS_C
AXP_HOT AXP_FLATTEN
auto execCvtqsC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS_M
AXP_HOT AXP_FLATTEN
auto execCvtqsM(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS_D
AXP_HOT AXP_FLATTEN
auto execCvtqsD(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS_SUIC
AXP_HOT AXP_FLATTEN
auto execCvtqsSuic(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS_SUIM
AXP_HOT AXP_FLATTEN
auto execCvtqsSuim(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS_SUI
AXP_HOT AXP_FLATTEN
auto execCvtqsSui(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQS_SUID
AXP_HOT AXP_FLATTEN
auto execCvtqsSuid(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT_C
AXP_HOT AXP_FLATTEN
auto execCvtqtC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT_M
AXP_HOT AXP_FLATTEN
auto execCvtqtM(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT_D
AXP_HOT AXP_FLATTEN
auto execCvtqtD(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT_SUIC
AXP_HOT AXP_FLATTEN
auto execCvtqtSuic(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT_SUIM
AXP_HOT AXP_FLATTEN
auto execCvtqtSuim(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT_SUI
AXP_HOT AXP_FLATTEN
auto execCvtqtSui(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQT_SUID
AXP_HOT AXP_FLATTEN
auto execCvtqtSuid(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTST_S
AXP_HOT AXP_FLATTEN
auto execCvtstS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtST(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPTUN_SU
AXP_HOT AXP_FLATTEN
auto execCmptunSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpT(fpBox::FpCompare::Un, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPTEQ_SU
AXP_HOT AXP_FLATTEN
auto execCmpteqSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpT(fpBox::FpCompare::Eq, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPTLT_SU
AXP_HOT AXP_FLATTEN
auto execCmptltSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpT(fpBox::FpCompare::Lt, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPTLE_SU
AXP_HOT AXP_FLATTEN
auto execCmptleSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpT(fpBox::FpCompare::Le, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS
AXP_HOT AXP_FLATTEN
auto execSqrts(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT
AXP_HOT AXP_FLATTEN
auto execSqrtt(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF_C
AXP_HOT AXP_FLATTEN
auto execSqrtfC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF
AXP_HOT AXP_FLATTEN
auto execSqrtf(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF_UC
AXP_HOT AXP_FLATTEN
auto execSqrtfUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF_U
AXP_HOT AXP_FLATTEN
auto execSqrtfU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF_SC
AXP_HOT AXP_FLATTEN
auto execSqrtfSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF_S
AXP_HOT AXP_FLATTEN
auto execSqrtfS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF_SUC
AXP_HOT AXP_FLATTEN
auto execSqrtfSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTF_SU
AXP_HOT AXP_FLATTEN
auto execSqrtfSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG_C
AXP_HOT AXP_FLATTEN
auto execSqrtgC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG
AXP_HOT AXP_FLATTEN
auto execSqrtg(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG_UC
AXP_HOT AXP_FLATTEN
auto execSqrtgUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG_U
AXP_HOT AXP_FLATTEN
auto execSqrtgU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG_SC
AXP_HOT AXP_FLATTEN
auto execSqrtgSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG_S
AXP_HOT AXP_FLATTEN
auto execSqrtgS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG_SUC
AXP_HOT AXP_FLATTEN
auto execSqrtgSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTG_SU
AXP_HOT AXP_FLATTEN
auto execSqrtgSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_C
AXP_HOT AXP_FLATTEN
auto execSqrtsC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_M
AXP_HOT AXP_FLATTEN
auto execSqrtsM(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_D
AXP_HOT AXP_FLATTEN
auto execSqrtsD(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_UC
AXP_HOT AXP_FLATTEN
auto execSqrtsUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_UM
AXP_HOT AXP_FLATTEN
auto execSqrtsUm(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_U
AXP_HOT AXP_FLATTEN
auto execSqrtsU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_UD
AXP_HOT AXP_FLATTEN
auto execSqrtsUd(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SUC
AXP_HOT AXP_FLATTEN
auto execSqrtsSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SUM
AXP_HOT AXP_FLATTEN
auto execSqrtsSum(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SU
AXP_HOT AXP_FLATTEN
auto execSqrtsSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SUD
AXP_HOT AXP_FLATTEN
auto execSqrtsSud(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SUIC
AXP_HOT AXP_FLATTEN
auto execSqrtsSuic(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SUIM
AXP_HOT AXP_FLATTEN
auto execSqrtsSuim(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SUI
AXP_HOT AXP_FLATTEN
auto execSqrtsSui(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTS_SUID
AXP_HOT AXP_FLATTEN
auto execSqrtsSuid(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtS(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_C
AXP_HOT AXP_FLATTEN
auto execSqrttC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_M
AXP_HOT AXP_FLATTEN
auto execSqrttM(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_D
AXP_HOT AXP_FLATTEN
auto execSqrttD(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_UC
AXP_HOT AXP_FLATTEN
auto execSqrttUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_UM
AXP_HOT AXP_FLATTEN
auto execSqrttUm(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_U
AXP_HOT AXP_FLATTEN
auto execSqrttU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_UD
AXP_HOT AXP_FLATTEN
auto execSqrttUd(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SUC
AXP_HOT AXP_FLATTEN
auto execSqrttSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SUM
AXP_HOT AXP_FLATTEN
auto execSqrttSum(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SU
AXP_HOT AXP_FLATTEN
auto execSqrttSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SUD
AXP_HOT AXP_FLATTEN
auto execSqrttSud(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SUIC
AXP_HOT AXP_FLATTEN
auto execSqrttSuic(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SUIM
AXP_HOT AXP_FLATTEN
auto execSqrttSuim(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SUI
AXP_HOT AXP_FLATTEN
auto execSqrttSui(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SQRTT_SUID
AXP_HOT AXP_FLATTEN
auto execSqrttSuid(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().sqrtT(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF_C
AXP_HOT AXP_FLATTEN
auto execAddfC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF_C
AXP_HOT AXP_FLATTEN
auto execSubfC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF_C
AXP_HOT AXP_FLATTEN
auto execMulfC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF_C
AXP_HOT AXP_FLATTEN
auto execDivfC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG_C
AXP_HOT AXP_FLATTEN
auto execCvtdgC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG_C
AXP_HOT AXP_FLATTEN
auto execAddgC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG_C
AXP_HOT AXP_FLATTEN
auto execSubgC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG_C
AXP_HOT AXP_FLATTEN
auto execMulgC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG_C
AXP_HOT AXP_FLATTEN
auto execDivgC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF_C
AXP_HOT AXP_FLATTEN
auto execCvtgfC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD_C
AXP_HOT AXP_FLATTEN
auto execCvtgdC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ_C
AXP_HOT AXP_FLATTEN
auto execCvtgqC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQF_C
AXP_HOT AXP_FLATTEN
auto execCvtqfC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQG_C
AXP_HOT AXP_FLATTEN
auto execCvtqgC(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF
AXP_HOT AXP_FLATTEN
auto execAddf(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF
AXP_HOT AXP_FLATTEN
auto execSubf(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF
AXP_HOT AXP_FLATTEN
auto execMulf(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF
AXP_HOT AXP_FLATTEN
auto execDivf(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG
AXP_HOT AXP_FLATTEN
auto execCvtdg(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG
AXP_HOT AXP_FLATTEN
auto execAddg(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG
AXP_HOT AXP_FLATTEN
auto execSubg(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG
AXP_HOT AXP_FLATTEN
auto execMulg(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG
AXP_HOT AXP_FLATTEN
auto execDivg(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPGEQ
AXP_HOT AXP_FLATTEN
auto execCmpgeq(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpG(fpBox::FpCompare::Eq, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPGLT
AXP_HOT AXP_FLATTEN
auto execCmpglt(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpG(fpBox::FpCompare::Lt, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPGLE
AXP_HOT AXP_FLATTEN
auto execCmpgle(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpG(fpBox::FpCompare::Le, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF
AXP_HOT AXP_FLATTEN
auto execCvtgf(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD
AXP_HOT AXP_FLATTEN
auto execCvtgd(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ
AXP_HOT AXP_FLATTEN
auto execCvtgq(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQF
AXP_HOT AXP_FLATTEN
auto execCvtqf(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTQG
AXP_HOT AXP_FLATTEN
auto execCvtqg(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtQG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF_UC
AXP_HOT AXP_FLATTEN
auto execAddfUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF_UC
AXP_HOT AXP_FLATTEN
auto execSubfUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF_UC
AXP_HOT AXP_FLATTEN
auto execMulfUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF_UC
AXP_HOT AXP_FLATTEN
auto execDivfUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG_UC
AXP_HOT AXP_FLATTEN
auto execCvtdgUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG_UC
AXP_HOT AXP_FLATTEN
auto execAddgUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG_UC
AXP_HOT AXP_FLATTEN
auto execSubgUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG_UC
AXP_HOT AXP_FLATTEN
auto execMulgUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG_UC
AXP_HOT AXP_FLATTEN
auto execDivgUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF_UC
AXP_HOT AXP_FLATTEN
auto execCvtgfUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD_UC
AXP_HOT AXP_FLATTEN
auto execCvtgdUc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ_VC
AXP_HOT AXP_FLATTEN
auto execCvtgqVc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF_U
AXP_HOT AXP_FLATTEN
auto execAddfU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF_U
AXP_HOT AXP_FLATTEN
auto execSubfU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF_U
AXP_HOT AXP_FLATTEN
auto execMulfU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF_U
AXP_HOT AXP_FLATTEN
auto execDivfU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG_U
AXP_HOT AXP_FLATTEN
auto execCvtdgU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG_U
AXP_HOT AXP_FLATTEN
auto execAddgU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG_U
AXP_HOT AXP_FLATTEN
auto execSubgU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG_U
AXP_HOT AXP_FLATTEN
auto execMulgU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG_U
AXP_HOT AXP_FLATTEN
auto execDivgU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF_U
AXP_HOT AXP_FLATTEN
auto execCvtgfU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD_U
AXP_HOT AXP_FLATTEN
auto execCvtgdU(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ_V
AXP_HOT AXP_FLATTEN
auto execCvtgqV(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF_SC
AXP_HOT AXP_FLATTEN
auto execAddfSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF_SC
AXP_HOT AXP_FLATTEN
auto execSubfSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF_SC
AXP_HOT AXP_FLATTEN
auto execMulfSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF_SC
AXP_HOT AXP_FLATTEN
auto execDivfSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG_SC
AXP_HOT AXP_FLATTEN
auto execCvtdgSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG_SC
AXP_HOT AXP_FLATTEN
auto execAddgSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG_SC
AXP_HOT AXP_FLATTEN
auto execSubgSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG_SC
AXP_HOT AXP_FLATTEN
auto execMulgSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG_SC
AXP_HOT AXP_FLATTEN
auto execDivgSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF_SC
AXP_HOT AXP_FLATTEN
auto execCvtgfSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD_SC
AXP_HOT AXP_FLATTEN
auto execCvtgdSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ_SC
AXP_HOT AXP_FLATTEN
auto execCvtgqSc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF_S
AXP_HOT AXP_FLATTEN
auto execAddfS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF_S
AXP_HOT AXP_FLATTEN
auto execSubfS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF_S
AXP_HOT AXP_FLATTEN
auto execMulfS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF_S
AXP_HOT AXP_FLATTEN
auto execDivfS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG_S
AXP_HOT AXP_FLATTEN
auto execCvtdgS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG_S
AXP_HOT AXP_FLATTEN
auto execAddgS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG_S
AXP_HOT AXP_FLATTEN
auto execSubgS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG_S
AXP_HOT AXP_FLATTEN
auto execMulgS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG_S
AXP_HOT AXP_FLATTEN
auto execDivgS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPGEQ_S
AXP_HOT AXP_FLATTEN
auto execCmpgeqS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpG(fpBox::FpCompare::Eq, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPGLT_S
AXP_HOT AXP_FLATTEN
auto execCmpgltS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpG(fpBox::FpCompare::Lt, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CMPGLE_S
AXP_HOT AXP_FLATTEN
auto execCmpgleS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cmpG(fpBox::FpCompare::Le, c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF_S
AXP_HOT AXP_FLATTEN
auto execCvtgfS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD_S
AXP_HOT AXP_FLATTEN
auto execCvtgdS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ_S
AXP_HOT AXP_FLATTEN
auto execCvtgqS(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF_SUC
AXP_HOT AXP_FLATTEN
auto execAddfSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF_SUC
AXP_HOT AXP_FLATTEN
auto execSubfSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF_SUC
AXP_HOT AXP_FLATTEN
auto execMulfSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF_SUC
AXP_HOT AXP_FLATTEN
auto execDivfSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG_SUC
AXP_HOT AXP_FLATTEN
auto execCvtdgSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG_SUC
AXP_HOT AXP_FLATTEN
auto execAddgSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG_SUC
AXP_HOT AXP_FLATTEN
auto execSubgSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG_SUC
AXP_HOT AXP_FLATTEN
auto execMulgSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG_SUC
AXP_HOT AXP_FLATTEN
auto execDivgSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF_SUC
AXP_HOT AXP_FLATTEN
auto execCvtgfSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD_SUC
AXP_HOT AXP_FLATTEN
auto execCvtgdSuc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ_SVC
AXP_HOT AXP_FLATTEN
auto execCvtgqSvc(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDF_SU
AXP_HOT AXP_FLATTEN
auto execAddfSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBF_SU
AXP_HOT AXP_FLATTEN
auto execSubfSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULF_SU
AXP_HOT AXP_FLATTEN
auto execMulfSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVF_SU
AXP_HOT AXP_FLATTEN
auto execDivfSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divF(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTDG_SU
AXP_HOT AXP_FLATTEN
auto execCvtdgSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtDG(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// ADDG_SU
AXP_HOT AXP_FLATTEN
auto execAddgSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().addG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// SUBG_SU
AXP_HOT AXP_FLATTEN
auto execSubgSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().subG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// MULG_SU
AXP_HOT AXP_FLATTEN
auto execMulgSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().mulG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// DIVG_SU
AXP_HOT AXP_FLATTEN
auto execDivgSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().divG(c.opA, c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGF_SU
AXP_HOT AXP_FLATTEN
auto execCvtgfSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGF(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGD_SU
AXP_HOT AXP_FLATTEN
auto execCvtgdSu(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGD(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTGQ_SV
AXP_HOT AXP_FLATTEN
auto execCvtgqSv(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    fpBox::FpExecCtx const ctx{ fpVariantFromEncoded(g.encoded), c.cpu->fpcr };
    fpBox::FpResult const r = fpBox::activeBackend().cvtGQ(c.opB, ctx);
    foldFpcrExc(c.cpu->fpcr, r.exc);
    return fpWrite(g, r.bits);
}

// CVTLQ
AXP_HOT AXP_FLATTEN
auto execCvtlq(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    uint64_t const fb = c.opB;
    uint32_t const lw = static_cast<uint32_t>((((fb >> 62) & 0x3ULL) << 30)
                                            | ((fb >> 29) & 0x3FFFFFFFULL));
    return fpWrite(g, static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(lw))));
}

// FCMOVEQ
AXP_HOT AXP_FLATTEN
auto execFcmoveq(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional move: Fc <- Fb when Fa == 0.0, else Fc unchanged.
    double const fa = std::bit_cast<double>(c.opA);
    if (fa == 0.0) return fpWrite(g, c.opB);
    BoxResult r; r.semFlags = g.semFlags; r.regWriteIdx = coreLib::kNoRegWrite; return r;
}

// FCMOVNE
AXP_HOT AXP_FLATTEN
auto execFcmovne(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional move: Fc <- Fb when Fa != 0.0, else Fc unchanged.
    double const fa = std::bit_cast<double>(c.opA);
    if (fa != 0.0) return fpWrite(g, c.opB);
    BoxResult r; r.semFlags = g.semFlags; r.regWriteIdx = coreLib::kNoRegWrite; return r;
}

// FCMOVLT
AXP_HOT AXP_FLATTEN
auto execFcmovlt(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional move: Fc <- Fb when Fa < 0.0, else Fc unchanged.
    double const fa = std::bit_cast<double>(c.opA);
    if (fa < 0.0) return fpWrite(g, c.opB);
    BoxResult r; r.semFlags = g.semFlags; r.regWriteIdx = coreLib::kNoRegWrite; return r;
}

// FCMOVGE
AXP_HOT AXP_FLATTEN
auto execFcmovge(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional move: Fc <- Fb when Fa >= 0.0, else Fc unchanged.
    double const fa = std::bit_cast<double>(c.opA);
    if (fa >= 0.0) return fpWrite(g, c.opB);
    BoxResult r; r.semFlags = g.semFlags; r.regWriteIdx = coreLib::kNoRegWrite; return r;
}

// FCMOVLE
AXP_HOT AXP_FLATTEN
auto execFcmovle(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional move: Fc <- Fb when Fa <= 0.0, else Fc unchanged.
    double const fa = std::bit_cast<double>(c.opA);
    if (fa <= 0.0) return fpWrite(g, c.opB);
    BoxResult r; r.semFlags = g.semFlags; r.regWriteIdx = coreLib::kNoRegWrite; return r;
}

// FCMOVGT
AXP_HOT AXP_FLATTEN
auto execFcmovgt(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional move: Fc <- Fb when Fa > 0.0, else Fc unchanged.
    double const fa = std::bit_cast<double>(c.opA);
    if (fa > 0.0) return fpWrite(g, c.opB);
    BoxResult r; r.semFlags = g.semFlags; r.regWriteIdx = coreLib::kNoRegWrite; return r;
}

// CVTQL
AXP_HOT AXP_FLATTEN
auto execCvtql(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    uint64_t const fb = c.opB;
    uint64_t const r = (((fb >> 30) & 0x3ULL) << 62) | ((fb & 0x3FFFFFFFULL) << 29);
    return fpWrite(g, r);
}

// CVTQL_V
AXP_HOT AXP_FLATTEN
auto execCvtqlV(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    uint64_t const fb = c.opB;
    uint64_t const r = (((fb >> 30) & 0x3ULL) << 62) | ((fb & 0x3FFFFFFFULL) << 29);
    return fpWrite(g, r);
}

// CVTQL_SV
AXP_HOT AXP_FLATTEN
auto execCvtqlSv(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    uint64_t const fb = c.opB;
    uint64_t const r = (((fb >> 30) & 0x3ULL) << 62) | ((fb & 0x3FFFFFFFULL) << 29);
    return fpWrite(g, r);
}

// FBEQ
AXP_HOT AXP_FLATTEN
auto execFbeq(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional branch: divert to PC+4 + SEXT(disp21)*4 when Fa == 0.0.
    double const fa = std::bit_cast<double>(c.opA);
    int64_t const disp = (static_cast<int64_t>(static_cast<int32_t>((g.encoded & 0x1FFFFFu) << 11)) >> 11) * 4;
    bool const taken = (fa == 0.0);
    BoxResult r; r.semFlags = g.semFlags;
    r.divert = taken;
    r.divertTarget = taken ? (g.pc + 4 + static_cast<uint64_t>(disp)) : 0;
    return r;
}

// FBLT
AXP_HOT AXP_FLATTEN
auto execFblt(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional branch: divert to PC+4 + SEXT(disp21)*4 when Fa < 0.0.
    double const fa = std::bit_cast<double>(c.opA);
    int64_t const disp = (static_cast<int64_t>(static_cast<int32_t>((g.encoded & 0x1FFFFFu) << 11)) >> 11) * 4;
    bool const taken = (fa < 0.0);
    BoxResult r; r.semFlags = g.semFlags;
    r.divert = taken;
    r.divertTarget = taken ? (g.pc + 4 + static_cast<uint64_t>(disp)) : 0;
    return r;
}

// FBLE
AXP_HOT AXP_FLATTEN
auto execFble(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional branch: divert to PC+4 + SEXT(disp21)*4 when Fa <= 0.0.
    double const fa = std::bit_cast<double>(c.opA);
    int64_t const disp = (static_cast<int64_t>(static_cast<int32_t>((g.encoded & 0x1FFFFFu) << 11)) >> 11) * 4;
    bool const taken = (fa <= 0.0);
    BoxResult r; r.semFlags = g.semFlags;
    r.divert = taken;
    r.divertTarget = taken ? (g.pc + 4 + static_cast<uint64_t>(disp)) : 0;
    return r;
}

// FBNE
AXP_HOT AXP_FLATTEN
auto execFbne(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional branch: divert to PC+4 + SEXT(disp21)*4 when Fa != 0.0.
    double const fa = std::bit_cast<double>(c.opA);
    int64_t const disp = (static_cast<int64_t>(static_cast<int32_t>((g.encoded & 0x1FFFFFu) << 11)) >> 11) * 4;
    bool const taken = (fa != 0.0);
    BoxResult r; r.semFlags = g.semFlags;
    r.divert = taken;
    r.divertTarget = taken ? (g.pc + 4 + static_cast<uint64_t>(disp)) : 0;
    return r;
}

// FBGE
AXP_HOT AXP_FLATTEN
auto execFbge(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional branch: divert to PC+4 + SEXT(disp21)*4 when Fa >= 0.0.
    double const fa = std::bit_cast<double>(c.opA);
    int64_t const disp = (static_cast<int64_t>(static_cast<int32_t>((g.encoded & 0x1FFFFFu) << 11)) >> 11) * 4;
    bool const taken = (fa >= 0.0);
    BoxResult r; r.semFlags = g.semFlags;
    r.divert = taken;
    r.divertTarget = taken ? (g.pc + 4 + static_cast<uint64_t>(disp)) : 0;
    return r;
}

// FBGT
AXP_HOT AXP_FLATTEN
auto execFbgt(InstructionGrain const& g, ExecCtx const& c) noexcept -> BoxResult
{
    // FP conditional branch: divert to PC+4 + SEXT(disp21)*4 when Fa > 0.0.
    double const fa = std::bit_cast<double>(c.opA);
    int64_t const disp = (static_cast<int64_t>(static_cast<int32_t>((g.encoded & 0x1FFFFFu) << 11)) >> 11) * 4;
    bool const taken = (fa > 0.0);
    BoxResult r; r.semFlags = g.semFlags;
    r.divert = taken;
    r.divertTarget = taken ? (g.pc + 4 + static_cast<uint64_t>(disp)) : 0;
    return r;
}

}  // namespace fBox
